#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

runApplication blockMesh
runApplication transformPoints -scale "(1 0 1)"
runApplication extrudeMesh

runApplication $(getApplication)
rhoPimpleFoam -postProcess -func yPlus > yPlus.log
rhoPimpleFoam -postProcess -func wallShearStress > wallShearStress.log
runApplication postProcess -func samplePwall
touch m.foam
pvpython makepngs.py
#------------------------------------------------------------------------------
